### ISSUE TITLE
Ability to publish on local registry

### ISSUE THREAD

**Issue by NimaSoroush** [opentable/oc#539]
Hi,

Is there any functionality to publish component to my local registry?

Use-case:
- This will help to test registry while running it locally without being dependent to s3 being in place
- It helps to compose registry docker in CI mode and publish your component to that registry and validate bunch of stuff (e.g. tests)

Currently running in local mode returns registry type as `oc-registry-local` which does not allow us to run `oc registry add <local registry>`. [Here](https://github.com/opentable/oc/blob/cc22411efb2e0b4ed5d19e82fa65248fd6e60c59/src/registry/routes/index.js#L25) and [here](https://github.com/opentable/oc/blob/cc22411efb2e0b4ed5d19e82fa65248fd6e60c59/src/cli/domain/registry.js#L49)

It also checks for s3 if not running on local mode. [Here](https://github.com/opentable/oc/blob/cc22411efb2e0b4ed5d19e82fa65248fd6e60c59/src/registry/domain/validators/registry-configuration.js#L86)

Any suggestion on this?

@matteofigus, @danrr

**Comment by NimaSoroush** [comment]
@matteofigus : Any thoughts?

**Comment by mattiaerre** [comment]
Hi @NimaSoroush are you able to explain a little bit more your scenario? I'd love to understand better and try to help.

**Comment by matteofigus** [comment]
Also, do you know about the fallbackRegistry functionality? https://github.com/opentable/oc/wiki/Cli#dev sounds like something you may find useful

**Comment by NimaSoroush** [comment]
Ok, I will open this a bit more. I want to have oc-registry independent to my component in the local and CI environment. This would allow me to publish my component to local registry. `oc dev .` is not a help here really as it been tightly coupled to my component location.

**Example of CI mode with `oc dev .`:**
```
build:
  image: node
  commands:
    - npm install
    - nohup oc dev . &   // run oc in background
    - npm test           // validate tests including unit tests and visual tests
```

**Drawbacks:**
- Need to run local OC within the same thread as the build is running
- Local OC might not be present by the time `npm test` been executed
- OC watch will be affected by various changes that might happen in component root

**Ideal solution**
```
build:
  image: node
  commands:
    - npm install
    - oc registry add <composed oc registry>
    - oc publish  .
    - npm test
compose:
  image: node-with-local-oc
  pull: true
```

Currently, this is not possible because of above issues.
Hope I explained my self better now

**Comment by matteofigus** [comment]
Ok, thanks, I see.
1) In linux, `command & command2` don't run on the same thread. They run together but they are independent.
2) I understand the problem. Here's how I usually do it:
* bring into dev dependencies `concurrently` and `wait-on`.
* add a npm script like 
```json
{
...
  "scripts": {
    "start-app": "oc dev . 3030",
    "run-tests": "wait-on http-get://localhost:3030 && jest",
    "test": "concurrently --kill-others 'npm run start-app' 'npm run run-tests'"
...
}
```
3) To simulate the "real registry", you need to run it with a watcher turned off. You can by running `oc dev . 3030 --hotReloading=false`.

I hope this is fine. The problem is that `oc dev` by design launches a registry that is exactly like a real one but without publishing - so your solution wouldn't work. Alternatively, you can setup a "real" registry connected to a different s3 account (for Testing purposes) and then publish and run the tests there. But I wouldn't recommend it unless you really need it (it adds costs and infrastructure - the oc dev should be a reliable and cheaper option for achieving that)

**Comment by NimaSoroush** [comment]
Hi @matteofigus,

The solution you suggested works fine. Thanks for that.
Just in case if you are interested, I've tried another way too and it almost worked, but it needs minor change in OC. Basically:

- Running local S3 server
- Configure local S3 endpoint in oc-registry server.js file
- OC will point to local s3 afterward

```
build:
  image: node
  commands:
    - npm install
    - oc registry add <composed oc registry>
    - oc publish  .
    - npm test
compose:
  image: node-with-local-oc
  pull: true
  
  image: local-s3
  pull: true
```

Currently, OC does not use `aws-sdk` S3 with `endpoint` and it uses `accessKeyId and secretAccessKey` for making connection, and that was blocking me to go toward this approach without touching OC.

I am going to close this issue as your suggestion solved the issue, but I think it would be nice to make my approach working as well. It basically needs one line code change in OC.

in S3.js
```
...
AWS.config.update({
    accessKeyId: 'conf.s3.key',
    secretAccessKey: conf.s3.secret,
    region: conf.s3.region,
    httpOptions: { timeout: conf.s3.timeout || 10000 }
  });
...
```

Thanks for your help,
Nima
